language: ruby

rvm:
  - 2.5.7

# run the check only when started from cron
script:
  - |
    if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then
      ./check_tumbleweed
    else
      echo "Not started from Travis cron, skipping the check"
    fi
